# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0003_userinfo_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ProfilePic',
            field=models.ImageField(upload_to='ProfilePic/'),
        ),
    ]
