# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notes_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_tag', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
