# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20161102_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=models.ImageField(upload_to=b'images/'),
        ),
    ]
