# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20161102_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='docfile',
        ),
        migrations.AddField(
            model_name='images',
            name='Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b'images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='Image_tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
