# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20161103_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='UserName',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='UserName',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
