# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20161103_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='my_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 9, 28, 6, 69677)),
        ),
    ]
