# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 23:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_notes_my_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Tag', models.CharField(max_length=10)),
                ('Description', models.TextField(max_length=100)),
                ('event_date', models.DateTimeField(default=datetime.datetime(2016, 11, 5, 23, 38, 8, 173875))),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='my_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 23, 38, 8, 173322)),
        ),
    ]
