# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_auto_20161107_1902'),
        ('notes', '0018_auto_20161108_1801'),
    ]

    operations = [
    ]
