# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0025_auto_20161108_1927'),
        ('notes', '0022_auto_20161108_1724'),
    ]

    operations = [
    ]
