# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0029_auto_20161110_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 6, 43, 29, 884209)),
        ),
        migrations.AlterField(
            model_name='document',
            name='my_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 6, 43, 29, 884181)),
        ),
        migrations.AlterField(
            model_name='event',
            name='my_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 11, 6, 43, 29, 881747)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_logout.UserInfo'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 6, 43, 29, 881160)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='my_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 6, 43, 29, 881131)),
        ),
    ]
